version = 0.1
[default.deploy.parameters]
stack_name = "oceanic-dev"
resolve_s3 = true
s3_prefix = "oceanic-dev"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
