AWSTemplateFormatVersion: 2010-09-09
Description: >-
  oceanic-cloud

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    CodeUri: "."
    Runtime: nodejs20.x
    Timeout: 3
    Architectures:
      - arm64
    MemorySize: 128

Resources:
  OceanicAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        DefaultAuthorizer: TokenAuthorizer
        Authorizers:
          TokenAuthorizer:
            FunctionArn: !GetAtt AuthFunction.Arn
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: authorizer.handler
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - src/functions/authorizer.ts
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: test.handler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref OceanicAPI
            Path: /
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        MainFields: module,main
        Format: esm
        Minify: false
        Sourcemap: false
        OutExtension:
          - .js=.mjs
        EntryPoints: 
          - src/functions/test.ts


Outputs:
  APIEndpoint:
    Description: URL of OceanicAPI
    Value: !Sub "https://${OceanicAPI}.execute-api.${AWS::Region}.amazonaws.com/prod"