openapi: 3.0.2
info:
  title: Oceanic API
  version: 0.1.0

components:
  responses:
    unauthorized:
      description: ID token is absent or malformed
  parameters:
    user:
      in: path
      name: user
      required: true
      schema:
        oneOf:
          - $ref: "schemas/uuid.json"
          - enum:
              - me

paths:
  /test:
    get:
      x-lambda-entry: test.ts
      x-required-permissions: null
      responses:
        '200':
          description: OK
  
  /login:
    description: This endpoint will match the API docs for AWS Cognito user pools
    post:
      description: "This endpoint will match [AWS Cognito](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-userpools-api-reference.html)"
      responses:
        "200":
          description: OK

  /users/{user}/documents:
    get:
      x-lambda-entry: document/list.ts
      summary: List documents.
      tags:
        - documents
      parameters:
        - $ref: "#/components/parameters/user"
      responses:
        "200":
          description: A list of all the documents 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "schemas/document.json"
        "401":
          $ref: "#/components/responses/unauthorized"
        "403":
          description: The authenticated user doesn't match the `user` parameter. (You're only allowed to list your own documents)
    post:
      x-lambda-entry: document/create.ts
      summary: Create a new document.
      tags:
        - documents
      requestBody:
        description: Metadata for the new document.
        content:
          application/json:
            schema:
              $ref: "schemas/document-create.json"
      responses:
        "200":
          description: The document was created successfully.
          content:
            application/json:
              schema:
                $ref: "schemas/document.json"
        "401":
          $ref: "#/components/responses/unauthorized"
        "403":
          description: "The authenticated user isn't allowed to create a document. This will happen if the authenticated user either doesn't match the `user` parameter (i.e. they're trying to create a document for another user), or they're no longer allowed write access on their account."

  /users/{user}/documents/{document}:
    get:
      x-lambda-entry: document/get.ts
      summary: Get document metadata.
      tags:
        - documents
      parameters:
        - $ref: "#/components/parameters/user"
        - in: path
          name: document
          required: true
          schema:
            $ref: "schemas/uuid.json"
      responses:
        "200":
          description: A document
          content:
            application/json:
              schema:
                $ref: "schemas/document.json"
        "401":
          $ref: "#/components/responses/unauthorized"
        "403":
          description: The authenticated user doesn't have access to this document
        "404":
          description: The document doesn't exist. This will only be returned if the authenticated user *would've* had access, had it existed. In other words, if the they're the same user as the one specified in the `user` parameter.
    patch:
      x-lambda-entry: document/update.ts
      summary: Update document metadata.
      tags:
        - documents
      parameters:
        - $ref: "#/components/parameters/user"
        - in: path
          name: document
          required: true
          schema:
            $ref: "schemas/uuid.json"
      requestBody:
        description: A JSON Patch document describing the changes to the metadata.
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: "schemas/json-patch.json"
      responses:
        "200":
          description: The updated metadata.
          content:
            application/json:
              schema:
                $ref: "schemas/document.json"
        "401":
          $ref: "#/components/responses/unauthorized"
        "403":
          description: The authenticated user doesn't have access to this document
        "404":
          description: The document doesn't exist. This will only be returned if the authenticated user *would've* had access, had it existed. In other words, if the they're the same user as the one specified in the `user` parameter.